apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::118686043688:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WALHHYJNAR3Q
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::118686043688:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T02:13:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1558"
  uid: 73f93ad4-addb-4e28-8aee-e734925e874f
