apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::118686043688:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-149VFQNDR7089
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::118686043688:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T06:29:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1757"
  uid: 682fcfe5-1e19-4847-b4e6-16d346194f07
